version: "3"
services:
  server:
    build: .
    container_name: notify
    restart: always
    volumes:
      - /var/log/notify:/var/log/notify
    networks:
      - notification

networks:
  notification:
    external: true
