version: "3"
services:
  server:
    build: .
    container_name: notify
    restart: always
    volumes:
      - /var/log/notify:/var/log/notify
    networks:
      - default
    labels:
      - homepage.group=Other
      - homepage.name=Notify
      - homepage.description=Notification server.
      - homepage.icon=apprise.png
      - homepage.server=local-docker
      - homepage.container=notify

networks:
  default:
