version: "3"
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    networks:
      - default
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /var/log/caddy:/log
      - data:/data
      - config:/config
    env_file:
      - .env
    environment:
      TZ: "Europe/Rome"
    labels:
      - homepage.group=Reverse Proxy
      - homepage.name=Caddy
      - homepage.description=Caddy reverse proxy.
      - homepage.icon=caddy.png
      - homepage.href=https://calisti.ddnsfree.com/
      - homepage.server=local-docker
      - homepage.container=caddy
      - homepage.widget.type=caddy
      - homepage.widget.url=http://caddy:2019

networks:
  default:

volumes:
  data:
  config:
