version: "3"
services:
  caddy:
    container_name: caddy
    image: caddy:2
    restart: always
    networks:
      - caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - data:/data
      - config:/config
      - /var/log/caddy:/log
    env_file:
      - .env
    environment:
      TZ: "Europe/Rome"
      
networks:
  caddy:
    external: true
    
volumes:
  data:
  config:
