version: "3"
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    networks:
      - caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /var/log/caddy:/log
      - data:/data
      - config:/config
    env_file:
      - .env
    environment:
      TZ: "Europe/Rome"

networks:
  caddy:
    external: true

volumes:
  data:
  config:
