version: "3"
services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: always
    env_file:
      - .env
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      INVITATIONS_ALLOWED: "false"
      LOG_FILE: "/log/vaultwarden.log"
      LOG_LEVEL: "warn"
      TZ: "Europe/Rome"
    networks:
      - caddy
    volumes:
      - vaultwarden_data:/data
      - /var/log/vaultwarden:/log

networks:
  caddy:
    external: true

volumes:
  vaultwarden_data:
    external: true
