version: "3"
services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: always
    networks:
      - caddy
    volumes:
      - vw_data:/data
      - /var/log/vaultwarden:/log
    env_file:
      - ./vaultwarden/.env

  vwbackup:
    container_name: vwbackup
    build: ./vwbackup
    restart: always
    volumes:
      - vw_data:/vw_data:ro
      - vw_backup:/vw_backup
    env_file:
      - ./vwbackup/.env

networks:
  caddy:
    external: true

volumes:
  vw_data:
  vw_backup:
