version: "3"
services:
  backup:
    build: .
    container_name: restic-backup
    hostname: resticdocker
    restart: always
    env_file:
      - .env
    environment:
      RUN_ON_STARTUP: "true"
      RESTIC_BACKUP_ARGS: >-
        --verbose
      RESTIC_FORGET_ARGS: >-
        --prune
        --keep-last 15
      PRE_COMMANDS: /hooks/pre_cmd_hook.sh
      POST_COMMANDS_FAILURE: /hooks/post_cmd_failure.sh
      POST_COMMANDS_INCOMPLETE: /hooks/post_cmd_incomplete.sh     
      BACKUP_CRON: "0 2 * * *"
      TZ: "Europe/Rome"
      NOTIFICATION_ADDRESS: "notify:5000"
    networks:
      - notify_default
    volumes:
      - ./rclone:/root/.config/rclone
      - data:/data
      - vaultwarden_data:/mnt/vw_data:ro

volumes:
  data:
  vaultwarden_data:
    external: true

networks:
  notify_default:
    external: true
