version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - data:/data
    restart: unless-stopped
    networks:
      - caddy_default
    labels:
      - homepage.group=Other
      - homepage.name=Portainer
      - homepage.description=Portainer WebUI.
      - homepage.href=https://calisti.ddnsfree.com/portainer
      - homepage.icon=portainer-alt.png
      - homepage.server=local-docker
      - homepage.container=portainer
      
volumes:
  data:

networks:
  caddy_default:
    external: true
