version: "3"
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    volumes:
      - ./data:/updater/data
    environment:
      TZ: "Europe/Rome"
    restart: always
    networks:
      - caddy_default

networks:
  caddy_default:
    external: true