version: "3"
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    volumes:
      - ./data:/updater/data
    environment:
      TZ: "Europe/Rome"
    restart: always
    networks:
      - caddy_default
    labels:
      - homepage.group=Other
      - homepage.name=DDNS Updater
      - homepage.description=DDNS-Updater WebUI.
      - homepage.icon=ddns-updater.png
      - homepage.href=https://calisti.ddnsfree.com/ddns
      - homepage.server=local-docker
      - homepage.container=ddns-updater

networks:
  caddy_default:
    external: true